# Generated by Django 3.1.3 on 2021-06-23 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='chocies',
            new_name='choices',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='social_link',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='testgrade',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='college',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone_num',
            field=models.CharField(default=11122223333, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='school_num',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='university',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learner',
            name='class_num',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learner',
            name='college',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='learner',
            name='major',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learner',
            name='phone_num',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learner',
            name='school_num',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learner',
            name='university',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='新建课程', max_length=30),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('deadline', models.DateField(default=django.utils.timezone.now)),
                ('grade', models.CharField(max_length=20)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='homework',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.homework'),
            preserve_default=False,
        ),
    ]
