# Generated by Django 3.1.3 on 2021-06-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_homeworkanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='grade',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
